# Generated by Django 5.0.4 on 2024-04-28 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_student_address_student_email_student_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
