# Generated by Django 5.0.4 on 2024-04-28 03:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_alter_student_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=25, null=True, validators=[django.core.validators.EmailValidator('Email address does not present')]),
        ),
    ]
