# Generated by Django 5.0.4 on 2024-04-28 03:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_alter_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=25, null=True, validators=[django.core.validators.EmailValidator('Email address is not valid')]),
        ),
    ]
