# Generated by Django 5.0.4 on 2024-04-28 03:38

import django.core.validators
import models.validators.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_student_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(150), django.core.validators.MinValueValidator(0), models.validators.validators.validate_even_number]),
        ),
    ]
